export type StatusFlag = { position: number; key: string; label: string; description: string; active: boolean };
export type StatusValues = Record<string, number | string | null> & { status_flags?: StatusFlag[] };
export type HistoryValue = number | string | null | StatusFlag[];
export type HistorySample = Record<string, HistoryValue> & { captured_at: string; status_flags?: StatusFlag[] };
export type BmsCell = { index: number; voltage: number; resistance_mohm?: number | null; wire_resistance_mohm?: number | null };
export type BmsStatus = {
  enabled: boolean;
  connected: boolean;
  source: string;
  address?: string | null;
  name?: string | null;
  protocol?: string | null;
  captured_at?: string | null;
  error?: string | null;
  stale?: boolean;
  last_error?: string | null;
  last_error_at?: string | null;
  cell_count?: number | null;
  cells: BmsCell[];
  min_cell_voltage?: number | null;
  max_cell_voltage?: number | null;
  delta_cell_voltage?: number | null;
  voltage?: number | null;
  current_a?: number | null;
  power_w?: number | null;
  capacity_percent?: number | null;
  remaining_capacity_ah?: number | null;
  nominal_capacity_ah?: number | null;
  cycle_count?: number | null;
  cycle_capacity_ah?: number | null;
  balance_current_a?: number | null;
  battery_t1_c?: number | null;
  battery_t2_c?: number | null;
  mos_temperature_c?: number | null;
  raw_summary?: Record<string, unknown>;
};
export type Status = { connected: boolean; mode: string | null; warnings: string | null; captured_at: string | null; error: string | null; status: StatusValues; bms?: BmsStatus | null };
export type Choice = { value: string; label: string; command: string };
export type Capability = { key: string; label: string; warning: string; choices: Choice[] };
export type CapabilitiesResponse = { capabilities: Capability[]; diagnostics?: Record<string, unknown> };
export type DiagnosticsResponse = { diagnostics: Record<string, unknown>; latest?: Status; bms?: BmsStatus | null };
export type BmsSettingKind = "number" | "switch";
export type BmsSettingCategory = "electrical" | "temperature" | "balancing" | "system" | "switches";
export type BmsSettingSpec = {
  key: string;
  label: string;
  category: BmsSettingCategory;
  kind: BmsSettingKind;
  unit: string;
  min?: number | null;
  max?: number | null;
  step?: number | null;
  verified: boolean;
  writable: boolean;
  voltage_scope?: "cell" | "delta" | null;
  cell_count?: number | null;
  note?: string | null;
};
export type BmsSettingsResponse = {
  supported: boolean;
  settings: BmsSettingSpec[];
  values: Record<string, number | boolean | null>;
  protocol: string;
  cell_count: number;
  captured_at: string;
  error?: string | null;
};
export type BmsSettingWriteResponse = {
  ok: boolean;
  key: string;
  old_value: number | boolean | null;
  new_value: number | boolean;
  verified_value: number | boolean | null;
  register: number;
  payload: string;
  settings: BmsSettingsResponse;
};
